# Generated by Django 4.1.7 on 2025-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='off',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
