# Generated by Django 4.1.7 on 2025-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('seller', 'فروشنده'), ('customer', 'مشتری')], default='customer', max_length=10),
        ),
    ]
